Ensure docker-compose.yml works with Podman Compose
Resolves the following error:

Error: short-name "postgres:15.5" did not resolve to an alias and no
unqualified-search registries are defined in
"/etc/containers/registries.conf"